var TASK_HEADERS=['Task ID','Task Name','Client ID','Project ID','Deliverable ID','Assigned To','Created By','Priority','Status','Start Date','Due Date','Completion Date','Notes','Created On','Updated On'];
var TASK_UPDATE_HEADERS=['Update ID','Task ID','Update By','Update Date','Status','Notes','Created On'];
var TASK_STATUSES=['To Do','In Progress','Pending Review','Completed','On Hold'];
var TASK_PRIORITIES=['Low','Medium','High','Critical'];

function ensureTaskSheets_(){
  var t=getOrCreateSheet_(APP.SHEETS.TASKS,TASK_HEADERS),u=getOrCreateSheet_(APP.SHEETS.TASK_UPDATES,TASK_UPDATE_HEADERS);
  [t,u].forEach(function(s){var n=s.getLastColumn();if(n){s.getRange(1,1,1,n).setFontWeight('bold').setBackground('#202124').setFontColor('#fff');s.setFrozenRows(1);}});
  return{tasks:t,updates:u};
}
function getTaskOptionsService_(){
  var c=requireAuth_(),a=[];
  var users=getCRMSpreadsheet_().getSheetByName(APP.SHEETS.USERS);
  if(users&&users.getLastRow()>1){var v=users.getDataRange().getValues();v.shift();v.forEach(function(r){var n=asText_(r[1]),role=asText_(r[2]),email=asText_(r[3]);if(n&&r[4]==='Active'&&(c.role!=='Employee'||n.toLowerCase()===c.name.toLowerCase()))a.push({name:n,role:role,email:email});});}
  var clients=[],projects=[],deliverables=[];
  var cs=getCRMSpreadsheet_().getSheetByName(APP.SHEETS.CLIENTS);
  if(cs&&cs.getLastRow()>1){var cv=cs.getDataRange().getValues(),ch=cv.shift();cv.forEach(function(r){if(r.some(function(x){return x!=='';})){var o={};ch.forEach(function(k,i){o[k]=r[i];});clients.push(serializeClient_(o));}});}
  var ps=getCRMSpreadsheet_().getSheetByName(APP.SHEETS.PROJECTS);
  if(ps&&ps.getLastRow()>1){var pv=ps.getDataRange().getValues(),ph=pv.shift();pv.forEach(function(r){if(r.some(function(x){return x!=='';})){var po={};ph.forEach(function(k,i){po[k]=r[i];});projects.push(serializeProject_(po));}});}
  var ds=getCRMSpreadsheet_().getSheetByName(APP.SHEETS.DELIVERABLES);
  if(ds&&ds.getLastRow()>1){var dv=ds.getDataRange().getValues(),dh=dv.shift();dv.forEach(function(r){if(r.some(function(x){return x!=='';})){var d={};dh.forEach(function(k,i){d[k]=r[i];});deliverables.push(d);}});}
  return{clients:clients,projects:projects,deliverables:deliverables,assignees:a,currentUser:{name:c.name,role:c.role},statuses:TASK_STATUSES,priorities:TASK_PRIORITIES};
}
function getTasksService_(){var c=requireAuth_(),s=ensureTaskSheets_().tasks;if(s.getLastRow()<2)return[];var v=s.getDataRange().getValues(),h=v.shift(),r=v.filter(function(x){return x.some(function(y){return y!=='';});}).map(function(x){var o={};h.forEach(function(k,i){o[k]=x[i];});return serializeTask_(o);});if(c.role==='Employee')r=r.filter(function(x){return asText_(x['Assigned To']).toLowerCase()===asText_(c.name).toLowerCase();});return r;}
function createTaskService_(d){var c=requireAuth_();if(c.role==='Employee')throw new Error('Employees cannot create tasks.');d=d||{};var n=asText_(d.taskName),cid=asText_(d.clientId),pid=asText_(d.projectId),did=asText_(d.deliverableId),a=asText_(d.assignedTo),p=asText_(d.priority)||'Medium',st=asText_(d.status)||'To Do';if(!n||!cid||!pid||!a)throw new Error('Task name, client, project and assignee are required.');if(TASK_PRIORITIES.indexOf(p)<0||TASK_STATUSES.indexOf(st)<0)throw new Error('Invalid task priority or status.');if(!getClientService_(cid))throw new Error('Client not found.');var pr=getProjectService_(pid);if(!pr||String(pr['Client ID'])!==cid)throw new Error('Project does not belong to the selected client.');if(did&&!getDeliverablesService_(pid).some(function(x){return String(x['Deliverable ID'])===did;}))throw new Error('Deliverable does not belong to the selected project.');if(!activeAssignee_(a,c))throw new Error('Selected assignee is not active.');var now=now_(),t={'Task ID':generateId_(CONFIG.ID_PREFIX.TASK),'Task Name':n,'Client ID':cid,'Project ID':pid,'Deliverable ID':did,'Assigned To':a,'Created By':c.name,'Priority':p,'Status':st,'Start Date':asText_(d.startDate),'Due Date':asText_(d.dueDate),'Completion Date':st==='Completed'?now:'','Notes':asText_(d.notes),'Created On':now,'Updated On':now};appendTask_(t);addTaskUpdate_(t['Task ID'],c.name,st,t.Notes||'Task created');recordActivity_('Task',t['Task ID'],'Created task: '+n+' · Assigned to: '+a);notifyTask_(a,'Task assigned: '+n,'A new task has been assigned to you in HYPEMARK CRM.\nDue: '+(t['Due Date']||'Not set'));return serializeTask_(t);}
function updateTaskService_(id,d){var c=requireAuth_(),s=ensureTaskSheets_().tasks,v=s.getDataRange().getValues(),h=v.shift();for(var i=0;i<v.length;i++)if(String(v[i][h.indexOf('Task ID')])===String(id)){var t={};h.forEach(function(k,j){t[k]=v[i][j];});var owner=asText_(t['Assigned To']).toLowerCase()===asText_(c.name).toLowerCase(),manager=['Admin','Manager'].indexOf(c.role)>=0;if(c.role==='Partner')throw new Error('Partners have view access to tasks.');if(c.role==='Employee'&&!owner)throw new Error('You can only update tasks assigned to you.');d=d||{};
    /* Accept both the canonical sheet field names and the lower-camel-case names used by the Tasks form. */
    var normalized={};
    Object.keys(d).forEach(function(k){
      var map={taskName:'Task Name',clientId:'Client ID',projectId:'Project ID',deliverableId:'Deliverable ID',assignedTo:'Assigned To',priority:'Priority',status:'Status',startDate:'Start Date',dueDate:'Due Date',notes:'Notes',UpdateNotes:'UpdateNotes',updateNotes:'UpdateNotes'};
      normalized[map[k]||k]=d[k];
    });
    if(manager){['Task Name','Client ID','Project ID','Deliverable ID','Assigned To','Priority','Status','Start Date','Due Date','Notes'].forEach(function(k){if(normalized[k]!==undefined)t[k]=asText_(normalized[k]);});if(TASK_PRIORITIES.indexOf(t.Priority)<0||TASK_STATUSES.indexOf(t.Status)<0)throw new Error('Invalid task priority or status.');}
    else{var ns=asText_(normalized.Status);if(ns&&['In Progress','Pending Review','On Hold'].indexOf(ns)<0)throw new Error('Employees can update only In Progress, Pending Review or On Hold.');if(ns)t.Status=ns;if(normalized.Notes!==undefined)t.Notes=asText_(normalized.Notes);}
    if(t.Status==='Completed'&&v[i][h.indexOf('Status')]!=='Completed')t['Completion Date']=now_();if(t.Status!=='Completed')t['Completion Date']='';t['Updated On']=now_();s.getRange(i+2,1,1,h.length).setValues([h.map(function(k){return t[k]===undefined?'':t[k];})]);addTaskUpdate_(id,c.name,t.Status,asText_(normalized.UpdateNotes||normalized.Notes)||('Status changed to '+t.Status));recordActivity_('Task',id,'Updated task: '+t['Task Name']+' · '+t.Status);if(t.Status==='Pending Review')notifyReviewers_(t);if(t.Status==='Completed')notifyTask_(t['Assigned To'],'Task completed: '+t['Task Name'],'Your task has been approved/completed in HYPEMARK CRM.');return serializeTask_(t);}throw new Error('Task not found.');}
function deleteTaskService_(id){var c=requirePermission_(AUTH_PERMISSIONS.USERS);if(c.role!=='Admin')throw new Error('Only Admin can delete tasks.');var s=ensureTaskSheets_().tasks,v=s.getDataRange().getValues(),h=v.shift();for(var i=0;i<v.length;i++)if(String(v[i][0])===String(id)){s.deleteRow(i+2);recordActivity_('Task',id,'Deleted task');return true;}throw new Error('Task not found.');}
function getTaskUpdatesService_(id){requireAuth_();var s=ensureTaskSheets_().updates;if(s.getLastRow()<2)return[];var v=s.getDataRange().getValues(),h=v.shift();return v.filter(function(r){return(!id||String(r[1])===String(id));}).map(function(r){var o={};h.forEach(function(k,i){o[k]=r[i];});return serializeTask_(o);});}
function getTaskDashboardStatsService_(){var t=getTasksService_(),d=new Date();d.setHours(0,0,0,0),w=new Date(d);w.setDate(d.getDate()-6);var o={today:0,dueToday:0,overdue:0,inProgress:0,pendingReview:0,completedWeek:0,total:t.length};t.forEach(function(x){var st=parseTaskDate_(x['Start Date']),du=parseTaskDate_(x['Due Date']),co=parseTaskDate_(x['Completion Date']);if(st&&+st===+d)o.today++;if(du&&+du===+d&&x.Status!=='Completed')o.dueToday++;if(du&&du<d&&x.Status!=='Completed')o.overdue++;if(x.Status==='In Progress')o.inProgress++;if(x.Status==='Pending Review')o.pendingReview++;if(co&&co>=w)o.completedWeek++;});return o;}
function approveTaskService_(id,ok,note){var c=requireAuth_();if(['Admin','Manager'].indexOf(c.role)<0)throw new Error('Only Admin or Manager can approve task work.');return updateTaskService_(id,{Status:ok?'Completed':'In Progress',Notes:note||'',UpdateNotes:note||(ok?'Approved and completed':'Returned for revision')});}
function appendTask_(t){var s=ensureTaskSheets_().tasks,h=s.getRange(1,1,1,s.getLastColumn()).getValues()[0];s.getRange(s.getLastRow()+1,1,1,h.length).setValues([h.map(function(k){return t[k]===undefined?'':t[k];})]);}
function addTaskUpdate_(id,by,st,n){var s=ensureTaskSheets_().updates,h=s.getRange(1,1,1,s.getLastColumn()).getValues()[0],t={'Update ID':generateId_(CONFIG.ID_PREFIX.TASK_UPDATE),'Task ID':id,'Update By':by,'Update Date':now_(),'Status':st,'Notes':n||'','Created On':now_()};s.getRange(s.getLastRow()+1,1,1,h.length).setValues([h.map(function(k){return t[k]===undefined?'':t[k];})]);}
function serializeTask_(o){var x={};Object.keys(o||{}).forEach(function(k){x[k]=o[k] instanceof Date?Utilities.formatDate(o[k],CONFIG.TIMEZONE,'dd-MMM-yyyy HH:mm'):o[k];});return x;}
function parseTaskDate_(v){if(!v)return null;var d=v instanceof Date?new Date(v):new Date(v);if(isNaN(d.getTime()))return null;d.setHours(0,0,0,0);return d;}
function activeAssignee_(name,c){if(c.role==='Employee')return asText_(name).toLowerCase()===asText_(c.name).toLowerCase();var s=getCRMSpreadsheet_().getSheetByName(APP.SHEETS.USERS);if(!s||s.getLastRow()<2)return false;var v=s.getDataRange().getValues();v.shift();return v.some(function(r){return asText_(r[1]).toLowerCase()===asText_(name).toLowerCase()&&r[4]==='Active';});}
function notifyTask_(name,subject,body){try{var s=getCRMSpreadsheet_().getSheetByName(APP.SHEETS.USERS);if(!s||s.getLastRow()<2)return;var v=s.getDataRange().getValues();v.shift();for(var i=0;i<v.length;i++)if(asText_(v[i][1]).toLowerCase()===asText_(name).toLowerCase()&&v[i][4]==='Active'&&v[i][3]){MailApp.sendEmail(String(v[i][3]),subject,body);return;}}catch(e){console.log(e);}}
function notifyReviewers_(t){try{var s=getCRMSpreadsheet_().getSheetByName(APP.SHEETS.USERS);if(!s||s.getLastRow()<2)return;var v=s.getDataRange().getValues();v.shift();var e=[];v.forEach(function(r){if(r[4]==='Active'&&['Admin','Manager'].indexOf(String(r[2]))>=0&&r[3]&&e.indexOf(String(r[3]))<0)e.push(String(r[3]));});if(e.length)MailApp.sendEmail(e.join(','),'Task ready for review: '+t['Task Name'],'Task '+t['Task Name']+' has been submitted for review in HYPEMARK CRM.');}catch(x){console.log(x);}}
function getDeliverableTaskSummaryService_(deliverableId){requireAuth_();var id=asText_(deliverableId);if(!id)throw new Error('Deliverable ID is required.');var s=ensureTaskSheets_().tasks;var out={deliverableId:id,total:0,completed:0,inProgress:0,pendingReview:0,toDo:0,onHold:0,overdue:0,progress:0};if(s.getLastRow()<2)return out;var v=s.getDataRange().getValues(),h=v.shift(),di=h.indexOf('Deliverable ID'),si=h.indexOf('Status'),dui=h.indexOf('Due Date');var today=new Date();today.setHours(0,0,0,0);v.forEach(function(r){if(String(r[di]||'')!==id)return;out.total++;var st=asText_(r[si]);if(st==='Completed')out.completed++;else if(st==='In Progress')out.inProgress++;else if(st==='Pending Review')out.pendingReview++;else if(st==='To Do')out.toDo++;else if(st==='On Hold')out.onHold++;var due=parseTaskDate_(r[dui]);if(due&&due<today&&st!=='Completed')out.overdue++;});out.progress=out.total?Math.round((out.completed/out.total)*100):0;return out;}
